### ISSUE TITLE
dump of the topology with IPv6 addresses

### ISSUE THREAD

**Issue by jorgesysg036** [netgroup/srv6-mininet-extensions#1]
Hi.

Can you herp me with the "/tmp/topology.json"

I didn´t find it? and really is very important it works over IPv6

thanks

**Comment by pierventre** [comment]
@cscarpitta 

Did you start the emulation with Mininet ?

**Comment by jorgesysg036** [comment]
Hi.

For the moment,  I installed mininet,and the extensions for SRv6, for start the emulation, I am new in this, and when i load the "srv6_mininet_extension.py" file, I can see the routers but with IPv4 and i was searching the "/tmp/topology.json" file for IPv6 that you said in the post, but i did not find it.

the direct Answer to your questions, is NOT, I am starting in the emulation.but i have not make the first emulation in mininet. 

Thanks for answer me.
I admire your work and your  papers.

**Comment by cscarpitta** [comment]
Hi,
could you send me the output of the command that you use to start the Mininet emulation?
`> sudo ./srv6_mininet_extensions.py --topology topo/example_srv6_topology.json`

**Comment by jorgesysg036** [comment]
```
Hi.
This is the result
```

root@mininet-virtual-machine:~/srv6-mininet-extensions# sudo ./srv6_mininet_extension.py --topology topo/example_srv6_topology.json 
*** Calculating Available Loopback Addresses
*** Calculating Available Router Ids
*** Calculating Available IP Networks
*** Calculating Available Mgmt Addresses
Unable to contact the remote controller at 127.0.0.1:6653
Unable to contact the remote controller at 127.0.0.1:6633
Setting remote controller to 127.0.0.1:6653
*** Creating network
*** Adding hosts:
ads1 ads2 mgmt sur1 
*** Adding switches:
br-mgmt1 
*** Adding links:
(1.00Mbit 1000 delay) (1.00Mbit 1000 delay) (ads1, ads2) (1000.00Mbit 0 delay) (1000.00Mbit 0 delay) (ads1, br-mgmt1) (5.00Mbit 200 delay) (5.00Mbit 200 delay) (ads1, sur1) (1000.00Mbit 0 delay) (1000.00Mbit 0 delay) (ads2, br-mgmt1) (10.00Mbit 100 delay) (10.00Mbit 100 delay) (ads2, sur1) (1000.00Mbit 0 delay) (1000.00Mbit 0 delay) (mgmt, br-mgmt1) (1000.00Mbit 0 delay) (1000.00Mbit 0 delay) (sur1, br-mgmt1) 
*** Configuring hosts
ads1 ads2 mgmt sur1 
*** Starting controller
c0 
*** Starting 1 switches
br-mgmt1 ...(1000.00Mbit 0 delay) (1000.00Mbit 0 delay) (1000.00Mbit 0 delay) (1000.00Mbit 0 delay) 
*** Starting CLI:

_### And when i look the ip nodes with a "dump", this is the result. It is working with IPv4_

mininet> dump
<SRv6Router ads1: ads1-eth0:10.0.0.1,ads1-eth1:None,ads1-eth2:None pid=12382> 
<SRv6Router ads2: ads2-eth0:10.0.0.2,ads2-eth1:None,ads2-eth2:None pid=12386> 
<SRv6Router mgmt: mgmt-eth0:10.0.0.3 pid=12390> 
<SRv6Router sur1: sur1-eth0:10.0.0.4,sur1-eth1:None,sur1-eth2:None pid=12394> 
<OVSBridge br-mgmt1: lo:127.0.0.1,br-mgmt1-eth1:None,br-mgmt1-eth2:None,br-mgmt1-eth3:None,br-mgmt1-eth4:None pid=12401> 
<RemoteController c0: 127.0.0.1:6653 pid=12374> 


Thanks for for answer me.

**Comment by pierventre** [comment]
I am not sure what `dump` command prints. If you want to print current configuration of the node you can just run nodename command. For example `ads1 ip a`.

Can you copy here the output of the command `ls -la /tmp` (in another terminal)

**Comment by jorgesysg036** [comment]
Hi.

Yeah, you have the reason, with the commad  ads1 ip a, i can see the ipv6 address.

mininet> ads2 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 fdff::2/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ads2-eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb state UP group default qlen 1000
    link/ether 8e:b0:ed:59:0a:ac brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::8cb0:edff:fe59:aac/64 scope link 
       valid_lft forever preferred_lft forever
3: ads2-eth0@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb state UP group default qlen 1000
    link/ether 6e:15:7c:d4:e9:13 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 2000::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::6c15:7cff:fed4:e913/64 scope link 
       valid_lft forever preferred_lft forever
4: ads2-eth2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb state UP group default qlen 1000
    link/ether da:ab:b9:25:b8:25 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::d8ab:b9ff:fe25:b825/64 scope link 
       valid_lft forever preferred_lft forever


And in the /tmp, this is the result.

root@mininet-virtual-machine:~# ls -l /tmp
total 568
drwxr-xr-x 2 root    root      4096 abr 23 13:33 ads1
drwxr-xr-x 2 root    root      4096 abr 23 13:33 ads2
-rw------- 1 mininet mininet      0 abr 19 22:03 config-err-KJSNPA
-rw------- 1 mininet mininet      0 abr 19 22:02 config-err-qDo2Ye
drwxr-xr-x 2 root    root      4096 abr 23 13:33 mgmt
-rw-r--r-- 1 root    root        51 abr 23 13:33 nodes.sh
drwx------ 2 mininet mininet   4096 abr 19 22:03 ssh-26gMgpVZIj0b
drwxr-xr-x 2 root    root      4096 abr 23 13:33 sur1
drwx------ 3 root    root      4096 abr 19 22:02 systemd-private-783cff13347049129ae9e8aff5eef979-bolt.service-3OT9iA
drwx------ 3 root    root      4096 abr 19 22:02 systemd-private-783cff13347049129ae9e8aff5eef979-colord.service-lD4zwx
drwx------ 3 root    root      4096 abr 19 22:04 systemd-private-783cff13347049129ae9e8aff5eef979-fwupd.service-1OwXS3
drwx------ 3 root    root      4096 abr 19 22:02 systemd-private-783cff13347049129ae9e8aff5eef979-rtkit-daemon.service-RXc9fL
drwx------ 3 root    root      4096 abr 19 22:02 systemd-private-783cff13347049129ae9e8aff5eef979-systemd-resolved.service-L1tCd9
drwx------ 3 root    root      4096 abr 19 22:02 systemd-private-783cff13347049129ae9e8aff5eef979-systemd-timesyncd.service-JV5ANM
-rw------- 1 mininet mininet 525838 abr 23 13:42 tmpaddon
-rw-r--r-- 1 root    root      1700 abr 23 13:33 topology.json


I can see the topology.json file, maybe i did not execute the command "sudo ./srv6_mininet_extensions.py --topology topo/example_srv6_topology.json"
i dont know if that is the reason because i did not see the "tolology.json" previosuly or some step that i omitted.

even in this moment  i can see in the file.

root@mininet-virtual-machine:~# cat /tmp/topology.json 
{
  "directed": true, 
  "graph": {}, 
  "links": [
    {
      "lhs_intf": "sur1-eth2", 
      "lhs_ip": "fdf0:0:0:2::2", 
      "rhs_intf": "ads2-eth2", 
      "rhs_ip": "fdf0:0:0:2::1", 
      "source": "sur1", 
      "target": "ads2"
    }, 
    {
      "lhs_intf": "sur1-eth1", 
      "lhs_ip": "fdf0:0:0:1::2", 
      "rhs_intf": "ads1-eth2", 
      "rhs_ip": "fdf0:0:0:1::1", 
      "source": "sur1", 
      "target": "ads1"
    }, 
    {
      "lhs_intf": "ads2-eth2", 
      "lhs_ip": "fdf0:0:0:2::1", 
      "rhs_intf": "sur1-eth2", 
      "rhs_ip": "fdf0:0:0:2::2", 
      "source": "ads2", 
      "target": "sur1"
    }, 
    {
      "lhs_intf": "ads2-eth1", 
      "lhs_ip": "fdf0::2", 
      "rhs_intf": "ads1-eth1", 
      "rhs_ip": "fdf0::1", 
      "source": "ads2", 
      "target": "ads1"
    }, 
    {
      "lhs_intf": "ads1-eth1", 
      "lhs_ip": "fdf0::1", 
      "rhs_intf": "ads2-eth1", 
      "rhs_ip": "fdf0::2", 
      "source": "ads1", 
      "target": "ads2"
    }, 
    {
      "lhs_intf": "ads1-eth2", 
      "lhs_ip": "fdf0:0:0:1::1", 
      "rhs_intf": "sur1-eth1", 
      "rhs_ip": "fdf0:0:0:1::2", 
      "source": "ads1", 
      "target": "sur1"
    }
  ], 
  "multigraph": true, 
  "nodes": [
    {
      "id": "sur1", 
      "loopbackip": "fdff::3/128", 
      "mgmtip": "2000::3/64", 
      "routerid": "0.0.0.3", 
      "type": "router"
    }, 
    {
      "id": "ads2", 
      "loopbackip": "fdff::2/128", 
      "mgmtip": "2000::2/64", 
      "routerid": "0.0.0.2", 
      "type": "router"
    }, 
    {
      "id": "ads1", 
      "loopbackip": "fdff::1/128", 
      "mgmtip": "2000::1/64", 
      "routerid": "0.0.0.1", 
      "type": "router"
    }
  ]

I believe with this  i can to start to emulate, what do you think about that?

Sorry for my ignorance, i am new in SR but i am very interest in this project and continue read about your papers and the projects over linux kernel with SRv6.

I am very grateful.







`

**Comment by pierventre** [comment]
Yes - you can start play with our project.

Consider that in the near feature we will update the project with new features @cscarpitta is developing.

 I do believe we can close the issue. If there are other problems in future - feel free to open a new one.

**Comment by jorgesysg036** [comment]
Really, Thanks so much

**Comment by pierventre** [comment]
ywc!
